image:
  repository: ghcr.io/heathouse/hammond
  tag: 0.0.25@sha256:23935bb5cfc2ae14ae815c0666f82d45ff61375ab58a720ab5ef7484a2bffe75
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10186

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            JWT_SECRET:
              secretKeyRef:
                name: secrets
                key: JWT_SECRET
            # manually define storage paths
            CONFIG: "{{.Values.persistence.config.mountPath }}"
            DATA: "{{.Values.persistence.assets.mountPath }}"

persistence:
  config:
    enabled: true
    mountPath: "/config"
  assets:
    enabled: true
    mountPath: "/assets"

portal:
  open:
    enabled: true
