image:
  repository: "ghcr.io/sct/overseerr"
  tag: "develop@sha256:bcd1ef5c2501c3210b3a8bbaf124f9f3b241f23a3f55038f80412f20e625bd17"
  pullPolicy: "IfNotPresent"
service:
  main:
    ports:
      main:
        port: 5055
        targetPort: 5055
persistence:
  config:
    enabled: true
    mountPath: "/app/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LOG_LEVEL: info
