image:
  repository: ghcr.io/linuxserver/mylar3
  tag: nightly@sha256:d17fb06df31ed37b22274450644cf63f5f0aab4f971a48d4f4134e2b66b6164b
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8090
        targetPort: 8090
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
